server:
  port: 8080
  servlet:
    contextPath: /ms-usuarios
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      

      
  main:
    allow-circular-references: true
    
  
        
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
            
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

logos:
  msit_logo_imss: /sintrans_data/LOGOS/logoImss.png
  msit_logo_sistema: /sintrans_data/LOGOS/logoSistema.png

endpoints:
   consulta-ooads: http://localhost:8090/dominio/
   paginado-unidad: http://localhost:8090/dominio/ooad/paginacion
   dominio-consulta: http://localhost:8090/mssivimss-mod-catalogos
   generico-paginado: http://localhost:8090/mssivimss-mod-catalogos/generico/paginado
   generico-consulta: http://localhost:8090/mssivimss-mod-catalogos/generico/consulta
   generico-crear: http://localhost:8090/mssivimss-mod-catalogos/generico/crear
   generico-actualizar: http://localhost:8090/mssivimss-mod-catalogos/generico/actualizar
   

jwt:
  secretkey-usuarios: funcionamuybien
  secretkey-dominios: funcionamuybiendominio
  expiration-milliseconds: 360

formato_fecha: '%d/%m/%Y'