server:
  port: 8080
  servlet:
    contextPath: /${spring.application.name}/v1
    
spring:
  application:
    name: mssivimss-cat-usuarios
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
 
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: ${msit_CONNECTION_DB}
    username: ${msit_USERNAME_DB}
    password: ${msit_PASSWORD_DB}
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
       max-lifetime: 1800000
       idle-timeout: 600000
       connection-timeout: 30000
       auto-commit: false
       maximum-pool-size: 7
       minimum-idle: 10
  environment: 'develop'


  main:
    allow-circular-references: true
    
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
            
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

endpoints:
   dominio: ${msit_CATALOGOS}
   generico-reportes: ${msit_REPORTES_GENERALES}

jwt:
  secretkey-usuarios: ${msit_SECRET_KEY}
  secretkey-dominios: ${msit_SECRET_KEY_DOMINIO}
  expiration-milliseconds: ${msit_SECRET_KEY_EXPIRATION}

formato_fecha: ${msit_FORMATO_FECHA}

management:
  endpoints:
    web:
      exposure:
        include:
          health,info,metrics
          
resilience4j.circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      msflujo:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        failureRateThreshold: ${msit_HILOS}
        slidingWindowType: COUNT_BASED
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: ${msit_TIEMPO_DURACION}
        permittedNumberOfCallsInHalfOpenState: ${msit_NUMERO_INTENTOS}
        slidingWindowSize: '5'
resilience4j.retry:
    retryAspectOrder: 2
    instances:
        msflujo:
           maxAttempts: ${msit_NUMERO_INTENTOS}
           waitDuration: ${msit_TIEMPO_DURACION}
resilience4j.timelimiter:
    timeLimiterAspectOrder: 3
    instances:
      msflujo:
        timeout-duration: ${msit_TIEMPO_DURACION}


ruta-log: ${msit_RUTA_LOG}

